spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: 10232312

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

jwt:
  claims:
    authorities:
      key: roles
    userId:
      key: user_id
  token:
    # "Bearer "
    prefix: Bearer
  header:
    string: Authorization