spring:
  data:
    mongodb:
      uri: mongodb://mongo-review-db:27017/review-service

  kafka:
    bootstrap-servers: broker:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8080