spring:
  application:
    name: review-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/review-service

  # Kafka producer properties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: ofosde:com.yilinglin10.reviewservice.event.consume.OrderFulfilledOrShippingDueEvent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8086